#!/usr/bin/env perl
use strict;
use warnings;
use Getopt::Long;
Getopt::Long::Configure("bundling");

my $delim = "\n";
my $sort;
GetOptions(
    "delim|d=s" => \$delim,
    "sorted|s"  => \$sort,
);

my @fields;
while (<>) {
    last if not /^##/;
    push @fields, $1 if /^##INFO=<ID=([^,]+)/;
}

@fields = sort { lc $a cmp lc $b } @fields
    if $sort;

print join $delim, @fields;
print "\n";
